//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Pname { get; set; }
        public string Pdescription { get; set; }
        public int Cid { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public int Amount { get; set; }
        public Nullable<int> B_id { get; set; }
        public Nullable<int> M_id { get; set; }
        public int Status { get; set; }
    }
}
