//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold_products
    {
        public int Id { get; set; }
        public int P_id { get; set; }
        public int U_id { get; set; }
        public int C_id { get; set; }
        public System.DateTime Date { get; set; }
        public string P_name { get; set; }
        public Nullable<int> P_amount { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
