//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WepAppMyDBEntities : DbContext
    {
        public WepAppMyDBEntities()
            : base("name=WepAppMyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<P_photo> P_photo { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sold_products> Sold_products { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
